{
    'name': 'IX Customization for AUI',
    'version': '1.0',
    'summary': '',
    'category': 'Education',
    'author': 'Omar IRAQI',
    'maintainer': '',
    'website': '',
    'license': 'LGPL-3',
    'contributors': [
        '',
    ],
    'depends': [
        'ixlms',
    ],
    'data': [
        'data/buildings.xml',
        'data/rooms.xml',
        'data/schools.xml',
        'data/disciplines.xml',
        'data/sessions.xml',
        'data/ucourses.xml',
        'data/corequisites.xml',
        'data/assessment_techniques.xml',
        'data/letter_grades.xml',
        'data/standard_events.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
