{
    'name': 'IX Quality Assurance',
    'version': '1.0',
    'summary': 'Supports auality assurance processes, including course portfolio management, as well as ILO and SO assessment.',
    'category': 'Liberal Arts Education',
    'author': 'Omar IRAQI',
    'maintainer': 'Omar IRAQI',
    'website': '',
    'license': 'LGPL-3',
    'contributors': [
        '',
    ],
    'depends': [
        'ixlms',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/course_view.xml',
        'views/course_program_view.xml',
        "views/accreditation_view.xml",
        "views/portfolio_view.xml",
        "views/program_view.xml",
        "views/assessment_view.xml",
        "views/lms_course_view.xml",
        "views/lms_chapter_view.xml",
        "views/acquisition_level_view.xml",
        "views/lms_assessment_view.xml",
        "views/lms_assessment_line_view.xml",
        'views/lms_module_view.xml',
        "views/school_view.xml",
        "views/quality_menu.xml",
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
