from . import activity
from . import school_owned
from . import course
from . import discipline
from . import faculty
from . import faculty_owned
from . import faculty_activity
from . import student_owned
from . import student
from . import student_activity
from . import faculty_student_shared
from . import res_users
from . import school
from . import school_activity
from . import staff
